package com.RestAPITestBDD;

import org.testng.Assert;
import org.testng.annotations.Test;

import io.restassured.response.Response;

import static io.restassured.RestAssured.given;
/*
 * given(): pre-requisite
 * ----------------------------------------
 * endpoint,request payload, path and query parameters, headers, Authentication
 * 
 * when(): Request
 * -------------------------------------------
 * GET,POST,PUT,PATCH,DELETE
 * 
 * then():validate Response
 * -----------------------------------------
 * status code,status message,response payload,header,cookies
 * 
 */
public class CookiesHeaderValidation {
  @Test
  public void HeaderTest()
  {
	Response res=given()
						.when().get("https://www.google.com/");
	
	//get all headers into console
	res.then().log().headers();
	  
	  System.out.println("----------------------");
	  
	  //single header -Content-Type: text/html; charset=ISO-8859-1
	  String actHeader=res.getHeader("Content-Type");
	  System.out.println("Header is: "+actHeader);
	  
	  //validate header
	  Assert.assertEquals(actHeader,"text/html; charset=ISO-8859-1");
	  System.out.println("Header matched!");
	  
	   
  }
  
  @Test
  public void cookiesTest()
  {
	  
	  Response res=given()
	  
			  		.when().get("https://www.google.com/");
	  
	  /*
	   * Cookies are generated by server and these are always dynamic
	   * Two cookies should not have same value
	   */
	  
	  
	  //get all the cookies 
	  res.then().log().cookies();
	  
	  System.out.println("-----------------------");
	  
	  //single cookie
	  String actCookie=res.getCookie("NID");
	  System.out.println(actCookie);
	  
	  
	  //validation
	  String expCookie="EAWCKAKK2QyHRqJdIsKjRfjI";
	  
//	  Assert.assertTrue(actCookie.contains(expCookie),"TestFail: Cookies are not same");
//	  System.out.println("Test pass: Cookies are same");
	  
	  Assert.assertFalse(actCookie.contains(expCookie),"Test Fail: Cookies are same");
	  System.out.println("Test pass: Cookies are not same");
	  
	  
  }
}
